CREATE TABLE IF NOT EXISTS `Notes`.
`Notes` 
(`ID` INT(255) NULL DEFAULT NULL , 
`Date` DATETIME(255) NULL DEFAULT CURRENT_TIMESTAMP , 
`Title` VARCHAR(255) NULL DEFAULT NULL , 
`Note` TEXT NULL DEFAULT NULL 
 PRIMARY KEY (title)
 ) 